### ISSUE TITLE
Insomnium is not actively being maintained

### ISSUE THREAD

**Issue by ZackarySantana** [stepci/awesome-api-clients#9]
Hey all, https://github.com/ArchGPT/insomnium is no longer being maintained. Thought the list should reflect that (maybe a note next to it or something or moved to a new section and it says it's app based)

**Comment by mishushakov** [comment]
Do you know anybody else who maintains a insomnia fork?

**Comment by ZackarySantana** [comment]
I don't unfortunately :/
